version: '3'

services:

  iam:
    build: 'keycloak-lb-postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DATABASE: 'keycloak'
      KEYCLOAK_USER: 'keycloak'
      KEYCLOAK_PASSWORD: 'somebettersecret'
      POSTGRES_PORT_5432_TCP_ADDR: 'db'
    ports:
      - '8080:8080'

  db:
    image: 'postgres:9.6.1'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'keycloak'
    ports:
      - '5432:5432'
